Replace deprecated UseCGroupMemoryLimitForHeap
Replace deprecated `UseCGroupMemoryLimitForHeap` with `UseContainerSupport`. Now if you leave empty the `javaHeap` parameter , it won't start due to :

```
Graylog Elasticsearch Version 7
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```